[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

[window]
padding.x = 10
padding.y = 10

dynamic_padding=true
dynamic_title = true

decorations = "Buttonless"
opacity = 0.9
blur = true

# Overrides dimensions
startup_mode = "Maximized"


# For a 1710x1112 resolution screen with a size 12 font

[window.dimensions]
columns = 239
lines = 69

[window.position]
x = 20
y= 100

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

