
[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

[window]
padding.x = 10
padding.y = 10

dynamic_title = true

decorations = "Buttonless"
opacity = 0.7
blur = true

# For a 1710x1112 resolution screen with a size 12 font

[window.dimensions]
columns = 236
lines = 68

[window.position]
x = 40
y= 120

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

