[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

[window]
padding.x = 20
padding.y = 10

dynamic_padding = true
dynamic_title = true

decorations = "Buttonless"
opacity = 1
blur = true
startup_mode = "Maximized"

[font]
normal.family = "DankMono Nerd Font Mono"
size = 17

offset.x = 0 # For letter spacing
offset.y = 5 # For line spacing

[general]
import = ["~/.config/alacritty/themes/moonfly.toml"]

[colors]
# Override the theme background color
primary = { background = "#191521" }
