[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

[window]
padding.x = 20
padding.y = 10

dynamic_padding=true
dynamic_title = true

decorations = "Buttonless"
opacity = 1
blur = true
startup_mode = "Maximized"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "DankMono Nerd Font Mono"
size = 16

[general]
import = [
	"~/.config/alacritty/themes/omni.toml"
]

